return {
    selected_track = 4,
    sequences = {
        {
            events = {
                {
                    type = "note",
                    time = 0,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 0.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 0.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    type = "note",
                    time = 0.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 1.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 1.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 1.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    type = "note",
                    time = 1.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 2.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 2.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 2.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    type = "note",
                    time = 2.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 3.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 3.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 3.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    time = 3.7,
                    velocity = 0.0,
                    note = 50.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 3.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    type = "note",
                    time = 4.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 48.0,
                },
                {
                    type = "note",
                    time = 4.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 4.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    type = "note",
                    time = 4.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 5.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 48.0,
                },
                {
                    type = "note",
                    time = 5.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 5.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    type = "note",
                    time = 5.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 6.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 48.0,
                },
                {
                    type = "note",
                    time = 6.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 6.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    type = "note",
                    time = 6.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 7.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 48.0,
                },
                {
                    type = "note",
                    time = 7.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 53.0,
                },
                {
                    type = "note",
                    time = 7.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    time = 7.6722222222222,
                    velocity = 0.0,
                    note = 53.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 7.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 57.0,
                },
                {
                    time = 7.8361111111111,
                    velocity = 0.0,
                    note = 57.0,
                    type = "note",
                },
                {
                    time = 7.8722222222222,
                    velocity = 0.0,
                    note = 48.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 8.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 8.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 8.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 8.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 9.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 9.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 9.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 9.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 10.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 10.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 10.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 10.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 11.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 11.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 11.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 11.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 12.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 12.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 12.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 12.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 13.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 13.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 13.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 13.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 14.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 14.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 14.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 14.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 15.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 46.0,
                },
                {
                    type = "note",
                    time = 15.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 15.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 55.0,
                },
                {
                    type = "note",
                    time = 15.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 50.0,
                },
                {
                    type = "note",
                    time = 16,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 16.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 16.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 16.75,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 17.0,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 17.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 17.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 17.75,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 18.0,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 18.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 18.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 18.75,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 19.0,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 19.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 19.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    time = 19.7,
                    velocity = 0.0,
                    note = 50.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 19.75,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 20.0,
                    duration = 0.2,
                    note = 48.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 20.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 20.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 20.75,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 21.0,
                    duration = 0.2,
                    note = 48.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 21.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 21.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 21.75,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 22.0,
                    duration = 0.2,
                    note = 48.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 22.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 22.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 22.75,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 23.0,
                    duration = 0.2,
                    note = 48.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 23.25,
                    duration = 0.2,
                    note = 53.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 23.5,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    time = 23.672222222222,
                    velocity = 0.0,
                    note = 53.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 23.75,
                    duration = 0.2,
                    note = 57.0,
                    velocity = 100,
                },
                {
                    time = 23.836111111111,
                    velocity = 0.0,
                    note = 57.0,
                    type = "note",
                },
                {
                    time = 23.872222222222,
                    velocity = 0.0,
                    note = 48.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 24.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 24.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 24.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 24.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 25.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 25.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 25.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 25.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 26.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 26.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 26.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 26.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 27.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 27.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 27.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 27.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 28.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 28.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 28.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 28.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 29.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 29.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 29.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 29.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 30.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 30.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 30.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 30.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 31.0,
                    duration = 0.2,
                    note = 46.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 31.25,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 31.5,
                    duration = 0.2,
                    note = 55.0,
                    velocity = 100,
                },
                {
                    type = "note",
                    time = 31.75,
                    duration = 0.2,
                    note = 50.0,
                    velocity = 100,
                },
            },
            loop_length = 32,
        },
        {
            events = {
                {
                    time = 0.030555555555556,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 0.19722222222222,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 0.19722222222222,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 0.49166666666667,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 0.725,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 0.725,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 0.96944444444444,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 1.2611111111111,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 1.2694444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 1.2694444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 1.4166666666667,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 1.4166666666667,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 1.9694444444444,
                    velocity = 100.0,
                    note = 68.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 2.5,
                    duration = 0.2,
                    velocity = 100,
                    note = 80,
                },
                {
                    time = 2.5111111111111,
                    velocity = 0.0,
                    note = 68.0,
                    type = "note",
                },
                {
                    time = 2.5111111111111,
                    velocity = 0.0,
                    note = 68.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 2.75,
                    duration = 0.2,
                    velocity = 100,
                    note = 80,
                },
                {
                    time = 2.9722222222222,
                    velocity = 0.0,
                    note = 80.0,
                    type = "note",
                },
                {
                    time = 2.975,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 3.0,
                    duration = 0.2,
                    velocity = 100,
                    note = 92,
                },
                {
                    time = 3.2166666666667,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 3.2166666666667,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 3.25,
                    duration = 0.2,
                    velocity = 100,
                    note = 92,
                },
                {
                    time = 3.3111111111111,
                    velocity = 0.0,
                    note = 92.0,
                    type = "note",
                },
                {
                    time = 3.4527777777778,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 3.6972222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 3.6972222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 3.7277777777778,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 3.9305555555556,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 3.9305555555556,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 4.5083333333333,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 4.675,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 4.675,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 5.0222222222222,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 5.2027777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 5.2027777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 5.4888888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 5.7472222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 5.7472222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 5.9472222222222,
                    velocity = 100.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    time = 6.3805555555556,
                    velocity = 0.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    time = 6.3805555555556,
                    velocity = 0.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    time = 6.9694444444444,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 7.1527777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 7.1527777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 7.4833333333333,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 7.6805555555556,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 7.6805555555556,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 8.0222222222222,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 8.275,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 8.3416666666667,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 8.3416666666667,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 8.4722222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 8.4722222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 9.0444444444444,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 9.3,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 9.3,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 9.3138888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 9.4361111111111,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 9.4361111111111,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 10.011111111111,
                    velocity = 100.0,
                    note = 70.0,
                    type = "note",
                },
                {
                    time = 10.438888888889,
                    velocity = 0.0,
                    note = 70.0,
                    type = "note",
                },
                {
                    time = 10.438888888889,
                    velocity = 0.0,
                    note = 70.0,
                    type = "note",
                },
                {
                    time = 11.013888888889,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 11.163888888889,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 11.163888888889,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 11.463888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 11.647222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 11.647222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 11.752777777778,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 11.911111111111,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 11.911111111111,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 12.488888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 12.65,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 12.65,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 15.002777777778,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 15.144444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 15.144444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 15.488888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 15.702777777778,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 15.702777777778,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 16.030555555556,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 16.197222222222,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 16.197222222222,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 16.491666666667,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 16.725,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 16.725,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 16.969444444444,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 17.261111111111,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 17.269444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 17.269444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 17.416666666667,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 17.416666666667,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 17.969444444444,
                    velocity = 100.0,
                    note = 68.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 18.5,
                    duration = 0.2,
                    note = 80,
                    velocity = 100,
                },
                {
                    time = 18.511111111111,
                    velocity = 0.0,
                    note = 68.0,
                    type = "note",
                },
                {
                    time = 18.511111111111,
                    velocity = 0.0,
                    note = 68.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 18.75,
                    duration = 0.2,
                    note = 80,
                    velocity = 100,
                },
                {
                    time = 18.972222222222,
                    velocity = 0.0,
                    note = 80.0,
                    type = "note",
                },
                {
                    time = 18.975,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 19.0,
                    duration = 0.2,
                    note = 92,
                    velocity = 100,
                },
                {
                    time = 19.216666666667,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 19.216666666667,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    type = "note",
                    time = 19.25,
                    duration = 0.2,
                    note = 92,
                    velocity = 100,
                },
                {
                    time = 19.311111111111,
                    velocity = 0.0,
                    note = 92.0,
                    type = "note",
                },
                {
                    time = 19.452777777778,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 19.697222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 19.697222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 19.727777777778,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 19.930555555556,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 19.930555555556,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 20.508333333333,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 20.675,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 20.675,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 21.022222222222,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 21.202777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 21.202777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 21.488888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 21.747222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 21.747222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 21.947222222222,
                    velocity = 100.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    time = 22.380555555556,
                    velocity = 0.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    time = 22.380555555556,
                    velocity = 0.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    time = 22.969444444444,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 23.152777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 23.152777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 23.483333333333,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 23.680555555556,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 23.680555555556,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 24.022222222222,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 24.275,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 24.341666666667,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 24.341666666667,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 24.472222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 24.472222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 25.044444444444,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 25.3,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 25.3,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 25.313888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 25.436111111111,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 25.436111111111,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 26.011111111111,
                    velocity = 100.0,
                    note = 70.0,
                    type = "note",
                },
                {
                    time = 26.438888888889,
                    velocity = 0.0,
                    note = 70.0,
                    type = "note",
                },
                {
                    time = 26.438888888889,
                    velocity = 0.0,
                    note = 70.0,
                    type = "note",
                },
                {
                    time = 27.013888888889,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 27.163888888889,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 27.163888888889,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 27.463888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 27.647222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 27.647222222222,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 27.752777777778,
                    velocity = 100.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 27.911111111111,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 27.911111111111,
                    velocity = 0.0,
                    note = 81.0,
                    type = "note",
                },
                {
                    time = 28.488888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 28.65,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 28.65,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 31.002777777778,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 31.144444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 31.144444444444,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 31.488888888889,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 31.702777777778,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 31.702777777778,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
            },
            loop_length = 32,
        },
        {
            events = {
                {
                    note = 84.0,
                    time = 17.008333333333,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 84.0,
                    time = 18.988888888889,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 84.0,
                    time = 18.988888888889,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 82.0,
                    time = 19.05,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 82.0,
                    time = 19.477777777778,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 82.0,
                    time = 19.477777777778,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 81.0,
                    time = 19.966666666667,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 81.0,
                    time = 21.669444444444,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 81.0,
                    time = 21.669444444444,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 79.0,
                    time = 21.963888888889,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 79.0,
                    time = 22.511111111111,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 79.0,
                    time = 22.511111111111,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 77.0,
                    time = 22.911111111111,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 77.0,
                    time = 23.413888888889,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 77.0,
                    time = 23.413888888889,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 76.0,
                    time = 23.894444444444,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 76.0,
                    time = 24.416666666667,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 76.0,
                    time = 24.416666666667,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 76.0,
                    time = 24.416666666667,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 76.0,
                    time = 24.427777777778,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 76.0,
                    time = 24.427777777778,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 74.0,
                    time = 24.736111111111,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 74.0,
                    time = 25.188888888889,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 74.0,
                    time = 25.188888888889,
                    velocity = 0.0,
                    type = "note",
                },
            },
            loop_length = 32,
        },
        {
            events = {
                {
                    type = "note",
                    note = 86.0,
                    duration = 0.2,
                    velocity = 100,
                    time = 14.0,
                },
                {
                    type = "note",
                    note = 89.0,
                    duration = 0.2,
                    velocity = 100,
                    time = 14.25,
                },
                {
                    type = "note",
                    note = 92.0,
                    duration = 0.2,
                    velocity = 100,
                    time = 14.5,
                },
                {
                    type = "note",
                    note = 93.0,
                    duration = 0.2,
                    velocity = 100,
                    time = 14.75,
                },
                {
                    type = "note",
                    note = 92.0,
                    duration = 0.2,
                    velocity = 100,
                    time = 15.0,
                },
                {
                    note = 92.0,
                    time = 15.183333333333,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 93.0,
                    time = 15.208333333333,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 86.0,
                    time = 15.216666666667,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 89.0,
                    time = 15.227777777778,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 88.0,
                    time = 23.927777777778,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 88.0,
                    time = 24.144444444444,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 88.0,
                    time = 24.144444444444,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 78.0,
                    time = 24.452777777778,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 78.0,
                    time = 24.616666666667,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 78.0,
                    time = 24.616666666667,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 86.0,
                    time = 24.736111111111,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 86.0,
                    time = 24.902777777778,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 86.0,
                    time = 24.902777777778,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 82.0,
                    time = 25.527777777778,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    note = 82.0,
                    time = 25.716666666667,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 82.0,
                    time = 25.716666666667,
                    velocity = 0.0,
                    type = "note",
                },
            },
            loop_length = 32,
        },
    },
    knob1 = 0.43499511480331,
    master_loop_length = 32,
    knob4 = 0.2678396999836,
    knob2 = 0.17790810763836,
    bpm = 100.0,
    pattern = 7,
    velocity_mode = 3,
    transpose = 12,
    knob3 = 0.0,
    metro_mode = 2,
    track_levels = {
        1,
        1,
        1.0,
        0.30009776353836,
    },
}
