return {
    bpm = 100.0,
    transpose = -24,
    sequences = {
        {
            loop_length = 16,
            events = {
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 0,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 0.25,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 0.5,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 0.5,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 0.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 0.75,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 0.75,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.0,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 1.0,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.25,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 1.25,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.5,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.5,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.5,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 1.75,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.75,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 1.75,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 1.75,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 2.0,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 2.0,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 2.25,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 2.25,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 2.5,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 2.5,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 2.5,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 2.75,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 2.75,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 2.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 2.75,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 2.75,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 2.75,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.0,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 3.0,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.0,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.0,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.25,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.25,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.25,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 3.25,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.5,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.5,
                    note = 79,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.5,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.5,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 3.5,
                    note = 48,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 3.5,
                    note = 55,
                    type = "note",
                },
                {
                    time = 3.6305555555556,
                    velocity = 0.0,
                    note = 64.0,
                    type = "note",
                },
                {
                    time = 3.6333333333333,
                    velocity = 0.0,
                    note = 60.0,
                    type = "note",
                },
                {
                    time = 3.65,
                    velocity = 0.0,
                    note = 67.0,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 4.0,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 4.25,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 4.5,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 4.5,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 4.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 4.75,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 5.0,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 5.0,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 5.25,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 5.25,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 5.25,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 5.5,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 5.5,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 5.5,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 5.5,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 5.75,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 5.75,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 5.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 5.75,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 5.75,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.0,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 6.0,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.25,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.25,
                    note = 53,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 6.25,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.5,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 6.5,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.5,
                    note = 53,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 6.5,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.75,
                    note = 77,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.75,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 6.75,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.75,
                    note = 53,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 6.75,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 6.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 7.0,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 7.0,
                    note = 77,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.0,
                    note = 53,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 7.0,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.25,
                    note = 77,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.25,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 7.25,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.25,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.25,
                    note = 53,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.5,
                    note = 77,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.5,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.5,
                    note = 65,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 7.5,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 7.5,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.5,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 7.5,
                    note = 48,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 7.5,
                    note = 53,
                    type = "note",
                },
                {
                    time = 7.5472222222222,
                    velocity = 0.0,
                    note = 60.0,
                    type = "note",
                },
                {
                    time = 7.5666666666667,
                    velocity = 0.0,
                    note = 65.0,
                    type = "note",
                },
                {
                    time = 7.6138888888889,
                    velocity = 0.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 8.0,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 8.25,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 8.25,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 8.5,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 8.5,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 8.75,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 8.75,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.0,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 9.0,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.25,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 9.25,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 9.25,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.5,
                    note = 71,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.5,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 9.5,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 9.5,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.75,
                    note = 71,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.75,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 9.75,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.75,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 9.75,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 10.0,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 10.0,
                    note = 71,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 10.25,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 10.25,
                    note = 71,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 10.25,
                    note = 74,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 10.5,
                    note = 74,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 10.5,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 10.5,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 10.5,
                    note = 71,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 10.75,
                    note = 71,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 10.75,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 10.75,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 10.75,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 10.75,
                    note = 74,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.0,
                    note = 74,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.0,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 11.0,
                    note = 50,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 11.0,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.25,
                    note = 50,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.25,
                    note = 79,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.25,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.25,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 11.25,
                    note = 74,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 11.25,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 11.25,
                    note = 55,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.5,
                    note = 74,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.5,
                    note = 50,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.5,
                    note = 79,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 11.5,
                    note = 59,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.5,
                    note = 67,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 11.5,
                    note = 71,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.5,
                    note = 62,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 11.5,
                    note = 55,
                    type = "note",
                },
                {
                    time = 11.55,
                    velocity = 0.0,
                    note = 62.0,
                    type = "note",
                },
                {
                    time = 11.591666666667,
                    velocity = 0.0,
                    note = 67.0,
                    type = "note",
                },
                {
                    time = 11.605555555556,
                    velocity = 0.0,
                    note = 71.0,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 12.0,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 12.25,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 12.5,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 12.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 12.75,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 12.75,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 13.0,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 13.0,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 13.25,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 13.25,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 13.5,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 13.5,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 13.5,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 13.75,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 13.75,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 13.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 13.75,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 13.75,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 14.0,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 14.0,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 14.25,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 14.25,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 14.5,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 14.5,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 14.5,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 14.5,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 14.75,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 14.75,
                    note = 72,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 14.75,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 14.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 14.75,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 14.75,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.0,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.0,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.0,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.0,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.25,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.25,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.25,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.25,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.5,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.5,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.5,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.5,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.5,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.75,
                    note = 60,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.75,
                    note = 76,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.75,
                    note = 48,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.75,
                    note = 64,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.75,
                    note = 81,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 100,
                    time = 15.75,
                    note = 52,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.75,
                    note = 69,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.75,
                    note = 57,
                    type = "note",
                },
                {
                    duration = 0.15,
                    velocity = 60,
                    time = 15.75,
                    note = 72,
                    type = "note",
                },
            },
        },
        {
            loop_length = 16,
            events = {
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 0.0,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 0.25,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 0.5,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 0.75,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 0.86944444444444,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    time = 0.86944444444444,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    time = 0.98888888888889,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 1.0,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 1.25,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 1.5,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 1.7083333333333,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 1.7083333333333,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 1.75,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 1.9888888888889,
                    velocity = 100.0,
                    note = 72.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 2.0,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 2.25,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 2.5,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 2.7444444444444,
                    velocity = 0.0,
                    note = 72.0,
                    type = "note",
                },
                {
                    time = 2.7444444444444,
                    velocity = 0.0,
                    note = 72.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 2.75,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 2.9777777777778,
                    velocity = 100.0,
                    note = 71.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 3.0,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 3.25,
                    note = 48.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 3.5,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 3.6194444444444,
                    velocity = 0.0,
                    note = 71.0,
                    type = "note",
                },
                {
                    time = 3.6194444444444,
                    velocity = 0.0,
                    note = 71.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 3.75,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 3.8083333333333,
                    velocity = 0.0,
                    note = 48.0,
                    type = "note",
                },
                {
                    time = 3.9861111111111,
                    velocity = 100.0,
                    note = 71.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 4.0,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 4.25,
                    note = 41.0,
                    type = "note",
                },
                {
                    time = 4.4138888888889,
                    velocity = 0.0,
                    note = 71.0,
                    type = "note",
                },
                {
                    time = 4.4138888888889,
                    velocity = 0.0,
                    note = 71.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 4.5,
                    note = 41.0,
                    type = "note",
                },
                {
                    time = 4.7361111111111,
                    velocity = 100.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 4.75,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 5.0,
                    note = 41.0,
                    type = "note",
                },
                {
                    time = 5.1361111111111,
                    velocity = 0.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    time = 5.1361111111111,
                    velocity = 0.0,
                    note = 69.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 5.25,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 5.5,
                    note = 41.0,
                    type = "note",
                },
                {
                    time = 5.5361111111111,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 5.5722222222222,
                    velocity = 100.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    time = 5.7166666666667,
                    velocity = 0.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    time = 5.7166666666667,
                    velocity = 0.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 5.75,
                    note = 41.0,
                    type = "note",
                },
                {
                    time = 5.875,
                    velocity = 100.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    time = 5.9777777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 5.9777777777778,
                    velocity = 0.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    time = 5.9777777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 5.9777777777778,
                    velocity = 0.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 6.0,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 6.25,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 6.5,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 6.75,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 7.0,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 7.25,
                    note = 41.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 7.5,
                    note = 41.0,
                    type = "note",
                },
                {
                    time = 7.5111111111111,
                    velocity = 100.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    time = 7.65,
                    velocity = 0.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    time = 7.65,
                    velocity = 0.0,
                    note = 93.0,
                    type = "note",
                },
                {
                    time = 7.7472222222222,
                    velocity = 0.0,
                    note = 41.0,
                    type = "note",
                },
                {
                    time = 7.9833333333333,
                    velocity = 100.0,
                    note = 91.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 8.0,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 8.1972222222222,
                    velocity = 0.0,
                    note = 91.0,
                    type = "note",
                },
                {
                    time = 8.1972222222222,
                    velocity = 0.0,
                    note = 91.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 8.25,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 8.5,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 8.75,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 9.0,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 9.25,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 9.5,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 9.75,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 10.0,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 10.033333333333,
                    velocity = 100.0,
                    note = 89.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 10.25,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 10.322222222222,
                    velocity = 0.0,
                    note = 89.0,
                    type = "note",
                },
                {
                    time = 10.322222222222,
                    velocity = 0.0,
                    note = 89.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 10.5,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 10.558333333333,
                    velocity = 100.0,
                    note = 72.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 10.75,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 10.969444444444,
                    velocity = 0.0,
                    note = 72.0,
                    type = "note",
                },
                {
                    time = 10.969444444444,
                    velocity = 0.0,
                    note = 72.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 11.0,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 11.25,
                    note = 43.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 11.5,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 11.505555555556,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 11.75,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 11.763888888889,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 11.763888888889,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 11.875,
                    velocity = 0.0,
                    note = 43.0,
                    type = "note",
                },
                {
                    time = 11.941666666667,
                    velocity = 100.0,
                    note = 89.0,
                    type = "note",
                },
                {
                    time = 12.0,
                    velocity = 100.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 12.0,
                    note = 45.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 12.25,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 12.391666666667,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    time = 12.391666666667,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    time = 12.452777777778,
                    velocity = 100.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    time = 12.486111111111,
                    velocity = 0.0,
                    note = 89.0,
                    type = "note",
                },
                {
                    time = 12.486111111111,
                    velocity = 0.0,
                    note = 89.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 12.5,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 12.505555555556,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 12.575,
                    velocity = 0.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    time = 12.575,
                    velocity = 0.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    time = 12.652777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 12.652777777778,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 12.75,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 12.961111111111,
                    velocity = 100.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    time = 12.975,
                    velocity = 100.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 13.0,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 13.116666666667,
                    velocity = 0.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    time = 13.116666666667,
                    velocity = 0.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 13.25,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 13.4,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    time = 13.4,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 13.5,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 13.502777777778,
                    velocity = 100.0,
                    note = 87.0,
                    type = "note",
                },
                {
                    time = 13.733333333333,
                    velocity = 0.0,
                    note = 87.0,
                    type = "note",
                },
                {
                    time = 13.733333333333,
                    velocity = 0.0,
                    note = 87.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 13.75,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 13.791666666667,
                    velocity = 100.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    time = 13.966666666667,
                    velocity = 0.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    time = 13.966666666667,
                    velocity = 0.0,
                    note = 88.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 14.0,
                    note = 45.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 14.25,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 14.461111111111,
                    velocity = 100.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 14.5,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 14.716666666667,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    time = 14.716666666667,
                    velocity = 0.0,
                    note = 74.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 14.75,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 14.986111111111,
                    velocity = 100.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 15.0,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 15.141666666667,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    time = 15.141666666667,
                    velocity = 0.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 15.25,
                    note = 45.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 15.5,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 15.533333333333,
                    velocity = 100.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 15.716666666667,
                    velocity = 100.0,
                    note = 76.0,
                    type = "note",
                },
                {
                    duration = 0.2,
                    velocity = 100,
                    time = 15.75,
                    note = 45.0,
                    type = "note",
                },
                {
                    time = 15.758333333333,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 15.758333333333,
                    velocity = 0.0,
                    note = 77.0,
                    type = "note",
                },
                {
                    time = 15.813888888889,
                    velocity = 0.0,
                    note = 45.0,
                    type = "note",
                },
            },
        },
    },
    metro_mode = 2,
    selected_track = 2,
    knob1 = 0.47214075922966,
    master_loop_length = 16,
    knob2 = 0.55327469110489,
    velocity_mode = 3,
    track_levels = {
        1,
        1,
        1,
        1,
    },
    knob3 = 0.50537633895874,
    knob4 = 0.47311827540398,
    pattern = 3,
}
