return {
    sequences = {
        {
            events = {
                {
                    duration = 0.2,
                    time = 0,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 0.25,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 0.5,
                    type = "note",
                    note = 77.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 0.75,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 1.0,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 1.25,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 1.5,
                    type = "note",
                    note = 77.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 1.75,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 1.9027777777778,
                    type = "note",
                    note = 70,
                    velocity = 0,
                },
                {
                    time = 1.9027777777778,
                    type = "note",
                    note = 74,
                    velocity = 0,
                },
                {
                    time = 1.9027777777778,
                    type = "note",
                    note = 77,
                    velocity = 0,
                },
                {
                    duration = 0.2,
                    time = 2.0,
                    type = "note",
                    note = 67.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 2.25,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 2.5,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 2.75,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 3.0,
                    type = "note",
                    note = 67.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 3.25,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 3.5,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 3.75,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    time = 3.8666666666667,
                    type = "note",
                    note = 67,
                    velocity = 0,
                },
                {
                    time = 3.8666666666667,
                    type = "note",
                    note = 74,
                    velocity = 0,
                },
                {
                    time = 3.8666666666667,
                    type = "note",
                    note = 70,
                    velocity = 0,
                },
                {
                    duration = 0.2,
                    time = 4.0,
                    type = "note",
                    note = 62.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 4.25,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 4.5,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 4.75,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 5.0,
                    type = "note",
                    note = 62.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 5.25,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 5.5,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 5.75,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 5.9833333333333,
                    type = "note",
                    note = 70,
                    velocity = 0,
                },
                {
                    time = 5.9833333333333,
                    type = "note",
                    note = 65,
                    velocity = 0,
                },
                {
                    time = 5.9833333333333,
                    type = "note",
                    note = 62,
                    velocity = 0,
                },
                {
                    duration = 0.2,
                    time = 6.0,
                    type = "note",
                    note = 63.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 6.25,
                    type = "note",
                    note = 67.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 6.5,
                    type = "note",
                    note = 72.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 6.75,
                    type = "note",
                    note = 67.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 7.0,
                    type = "note",
                    note = 63.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 7.25,
                    type = "note",
                    note = 67.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 7.5,
                    type = "note",
                    note = 72.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 7.75,
                    type = "note",
                    note = 67.0,
                    velocity = 100,
                },
                {
                    time = 7.9638888888889,
                    type = "note",
                    note = 72,
                    velocity = 0,
                },
                {
                    time = 7.9638888888889,
                    type = "note",
                    note = 67,
                    velocity = 0,
                },
                {
                    time = 7.9638888888889,
                    type = "note",
                    note = 63,
                    velocity = 0,
                },
                {
                    duration = 0.2,
                    time = 8.0,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 8.25,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 8.5,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 8.75,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 9.0,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 9.25,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 9.5,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 9.75,
                    type = "note",
                    note = 70.0,
                    velocity = 100,
                },
                {
                    time = 9.9555555555556,
                    type = "note",
                    note = 70,
                    velocity = 0,
                },
                {
                    time = 9.9555555555556,
                    type = "note",
                    note = 65,
                    velocity = 0,
                },
                {
                    time = 9.9555555555556,
                    type = "note",
                    note = 74,
                    velocity = 0,
                },
                {
                    duration = 0.2,
                    time = 10.0,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 10.25,
                    type = "note",
                    note = 72.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 10.5,
                    type = "note",
                    note = 75.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 10.75,
                    type = "note",
                    note = 72.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 11.0,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 11.25,
                    type = "note",
                    note = 72.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 11.5,
                    type = "note",
                    note = 75.0,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 11.75,
                    type = "note",
                    note = 72.0,
                    velocity = 100,
                },
            },
            loop_length = 12,
        },
        {
            events = {
                {
                    time = 0.0,
                    type = "note",
                    note = 77.0,
                    velocity = 100.0,
                },
                {
                    time = 1.0,
                    type = "note",
                    note = 77.0,
                    velocity = 0.0,
                },
                {
                    time = 1.0,
                    type = "note",
                    note = 77.0,
                    velocity = 0.0,
                },
                {
                    time = 1.5138888888889,
                    type = "note",
                    note = 77.0,
                    velocity = 100.0,
                },
                {
                    time = 1.6194444444444,
                    type = "note",
                    note = 77.0,
                    velocity = 0.0,
                },
                {
                    time = 1.6194444444444,
                    type = "note",
                    note = 77.0,
                    velocity = 0.0,
                },
                {
                    time = 2.0861111111111,
                    type = "note",
                    note = 75.0,
                    velocity = 100.0,
                },
                {
                    time = 2.5138888888889,
                    type = "note",
                    note = 75.0,
                    velocity = 0.0,
                },
                {
                    time = 2.5138888888889,
                    type = "note",
                    note = 75.0,
                    velocity = 0.0,
                },
                {
                    time = 2.5777777777778,
                    type = "note",
                    note = 74.0,
                    velocity = 100.0,
                },
                {
                    time = 2.7277777777778,
                    type = "note",
                    note = 74.0,
                    velocity = 0.0,
                },
                {
                    time = 2.7277777777778,
                    type = "note",
                    note = 74.0,
                    velocity = 0.0,
                },
                {
                    time = 3.0333333333333,
                    type = "note",
                    note = 72.0,
                    velocity = 100.0,
                },
                {
                    time = 3.1416666666667,
                    type = "note",
                    note = 72.0,
                    velocity = 0.0,
                },
                {
                    time = 3.1416666666667,
                    type = "note",
                    note = 72.0,
                    velocity = 0.0,
                },
                {
                    time = 3.5166666666667,
                    type = "note",
                    note = 70.0,
                    velocity = 100.0,
                },
                {
                    time = 3.6944444444444,
                    type = "note",
                    note = 70.0,
                    velocity = 0.0,
                },
                {
                    time = 3.6944444444444,
                    type = "note",
                    note = 70.0,
                    velocity = 0.0,
                },
                {
                    time = 3.7305555555556,
                    type = "note",
                    note = 70.0,
                    velocity = 100.0,
                },
                {
                    time = 4.7027777777778,
                    type = "note",
                    note = 70.0,
                    velocity = 0.0,
                },
                {
                    time = 4.7027777777778,
                    type = "note",
                    note = 70.0,
                    velocity = 0.0,
                },
                {
                    time = 5.4888888888889,
                    type = "note",
                    note = 65.0,
                    velocity = 100.0,
                },
                {
                    time = 5.6444444444444,
                    type = "note",
                    note = 65.0,
                    velocity = 0.0,
                },
                {
                    time = 5.6444444444444,
                    type = "note",
                    note = 65.0,
                    velocity = 0.0,
                },
                {
                    time = 6.0027777777778,
                    type = "note",
                    note = 66.0,
                    velocity = 100.0,
                },
                {
                    time = 6.5611111111111,
                    type = "note",
                    note = 65.0,
                    velocity = 100.0,
                },
                {
                    time = 6.6,
                    type = "note",
                    note = 66.0,
                    velocity = 0.0,
                },
                {
                    time = 6.6,
                    type = "note",
                    note = 66.0,
                    velocity = 0.0,
                },
                {
                    time = 6.7,
                    type = "note",
                    note = 65.0,
                    velocity = 0.0,
                },
                {
                    time = 6.7,
                    type = "note",
                    note = 65.0,
                    velocity = 0.0,
                },
                {
                    time = 7.0083333333333,
                    type = "note",
                    note = 63.0,
                    velocity = 100.0,
                },
                {
                    time = 7.1805555555556,
                    type = "note",
                    note = 63.0,
                    velocity = 0.0,
                },
                {
                    time = 7.1805555555556,
                    type = "note",
                    note = 63.0,
                    velocity = 0.0,
                },
                {
                    time = 7.5111111111111,
                    type = "note",
                    note = 62.0,
                    velocity = 100.0,
                },
                {
                    time = 8.8916666666667,
                    type = "note",
                    note = 62.0,
                    velocity = 0.0,
                },
                {
                    time = 8.8916666666667,
                    type = "note",
                    note = 62.0,
                    velocity = 0.0,
                },
                {
                    time = 9.4944444444444,
                    type = "note",
                    note = 62.0,
                    velocity = 100.0,
                },
                {
                    time = 9.6388888888889,
                    type = "note",
                    note = 62.0,
                    velocity = 0.0,
                },
                {
                    time = 9.6388888888889,
                    type = "note",
                    note = 62.0,
                    velocity = 0.0,
                },
                {
                    time = 9.6416666666667,
                    type = "note",
                    note = 62.0,
                    velocity = 100.0,
                },
                {
                    time = 9.6555555555556,
                    type = "note",
                    note = 62.0,
                    velocity = 0.0,
                },
                {
                    time = 9.6555555555556,
                    type = "note",
                    note = 62.0,
                    velocity = 0.0,
                },
                {
                    time = 9.9944444444444,
                    type = "note",
                    note = 63.0,
                    velocity = 100.0,
                },
                {
                    time = 10.5,
                    type = "note",
                    note = 63.0,
                    velocity = 0.0,
                },
                {
                    time = 10.5,
                    type = "note",
                    note = 63.0,
                    velocity = 0.0,
                },
                {
                    time = 10.986111111111,
                    type = "note",
                    note = 65.0,
                    velocity = 100.0,
                },
                {
                    time = 11.230555555556,
                    type = "note",
                    note = 65.0,
                    velocity = 0.0,
                },
                {
                    time = 11.230555555556,
                    type = "note",
                    note = 65.0,
                    velocity = 0.0,
                },
            },
            loop_length = 12,
        },
        {
            events = {
                {
                    duration = 0.2,
                    time = 0.5,
                    type = "note",
                    note = 58,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 0.75,
                    type = "note",
                    note = 58,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 1.0,
                    type = "note",
                    note = 58,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 1.25,
                    type = "note",
                    note = 58,
                    velocity = 100,
                },
                {
                    time = 1.4722222222222,
                    type = "note",
                    note = 58.0,
                    velocity = 0.0,
                },
                {
                    duration = 0.2,
                    time = 2.5,
                    type = "note",
                    note = 57,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 2.75,
                    type = "note",
                    note = 57,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 3.0,
                    type = "note",
                    note = 57,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 3.25,
                    type = "note",
                    note = 57,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 3.5,
                    type = "note",
                    note = 57,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 3.75,
                    type = "note",
                    note = 57,
                    velocity = 60,
                },
                {
                    time = 3.8944444444444,
                    type = "note",
                    note = 57.0,
                    velocity = 0.0,
                },
                {
                    duration = 0.2,
                    time = 4.0,
                    type = "note",
                    note = 62,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 4.25,
                    type = "note",
                    note = 62,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 4.5,
                    type = "note",
                    note = 62,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 4.75,
                    type = "note",
                    note = 62,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 5.0,
                    type = "note",
                    note = 62,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 5.25,
                    type = "note",
                    note = 62,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 5.5,
                    type = "note",
                    note = 62,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 5.75,
                    type = "note",
                    note = 62,
                    velocity = 60,
                },
                {
                    time = 5.8416666666667,
                    type = "note",
                    note = 62.0,
                    velocity = 0.0,
                },
                {
                    duration = 0.2,
                    time = 6.0,
                    type = "note",
                    note = 51,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 6.25,
                    type = "note",
                    note = 51,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 6.5,
                    type = "note",
                    note = 51,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 6.75,
                    type = "note",
                    note = 51,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 7.0,
                    type = "note",
                    note = 51,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 7.25,
                    type = "note",
                    note = 51,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 7.5,
                    type = "note",
                    note = 51,
                    velocity = 60,
                },
                {
                    time = 7.625,
                    type = "note",
                    note = 51.0,
                    velocity = 0.0,
                },
                {
                    duration = 0.2,
                    time = 8.0,
                    type = "note",
                    note = 50,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 8.25,
                    type = "note",
                    note = 50,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 8.5,
                    type = "note",
                    note = 50,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 8.75,
                    type = "note",
                    note = 50,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 9.0,
                    type = "note",
                    note = 50,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 9.25,
                    type = "note",
                    note = 50,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 9.5,
                    type = "note",
                    note = 50,
                    velocity = 60,
                },
                {
                    time = 9.7,
                    type = "note",
                    note = 50.0,
                    velocity = 0.0,
                },
                {
                    duration = 0.2,
                    time = 10.0,
                    type = "note",
                    note = 51,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 10.25,
                    type = "note",
                    note = 51,
                    velocity = 100,
                },
                {
                    duration = 0.2,
                    time = 10.5,
                    type = "note",
                    note = 51,
                    velocity = 100,
                },
                {
                    time = 10.536111111111,
                    type = "note",
                    note = 51.0,
                    velocity = 0.0,
                },
                {
                    duration = 0.2,
                    time = 11.0,
                    type = "note",
                    note = 53,
                    velocity = 60,
                },
                {
                    duration = 0.2,
                    time = 11.25,
                    type = "note",
                    note = 53,
                    velocity = 100,
                },
                {
                    time = 11.466666666667,
                    type = "note",
                    note = 53.0,
                    velocity = 0.0,
                },
            },
            loop_length = 12,
        },
    },
    velocity_mode = 3,
    knob4 = 0.2111437022686,
    transpose = -12,
    knob1 = 0.55620723962784,
    knob3 = 0.45943304896355,
    selected_track = 3,
    master_loop_length = 12,
    metro_mode = 1,
    knob2 = 0.42913001775742,
    track_levels = {
        1.0,
        1.0,
        1.0,
        1.0,
    },
    pattern = 2,
}
