return {
    knob4 = 0.52590417861938,
    sequences = {
        {
            loop_length = 16,
            events = {
                {
                    time = 0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 0.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 0.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 0.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 1.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 79.0,
                },
                {
                    time = 1.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 1.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 1.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 2.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 2.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 2.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 2.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 3.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 79.0,
                },
                {
                    time = 3.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 3.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 3.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 3.8222222222222,
                    note = 79.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 3.8305555555556,
                    note = 71.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 3.8333333333333,
                    note = 76.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 3.8722222222222,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 3.8777777777778,
                    note = 67.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 4.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 4.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 66.0,
                },
                {
                    time = 4.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 4.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 74.0,
                },
                {
                    time = 5.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 78.0,
                },
                {
                    time = 5.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 74.0,
                },
                {
                    time = 5.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 5.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 66.0,
                },
                {
                    time = 6.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 6.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 66.0,
                },
                {
                    time = 6.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 6.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 74.0,
                },
                {
                    time = 7.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 78.0,
                },
                {
                    time = 7.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 74.0,
                },
                {
                    time = 7.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 7.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 66.0,
                },
                {
                    time = 7.8944444444444,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.9027777777778,
                    note = 66.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.9166666666667,
                    note = 71.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.9194444444444,
                    note = 74.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.9222222222222,
                    note = 78.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 8.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 8.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 8.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 72.0,
                },
                {
                    time = 8.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 9.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 81.0,
                },
                {
                    time = 9.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 9.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 72.0,
                },
                {
                    time = 9.6694444444444,
                    note = 81.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 9.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 9.7527777777778,
                    note = 67.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 9.7555555555556,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 9.825,
                    note = 72.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 10.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 10.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 72.0,
                },
                {
                    time = 10.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 11.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 78.0,
                },
                {
                    time = 11.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 76.0,
                },
                {
                    time = 11.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 72.0,
                },
                {
                    time = 11.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 67.0,
                },
                {
                    time = 12.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 12.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 60.0,
                },
                {
                    time = 12.094444444444,
                    note = 78.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 12.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 12.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 69.0,
                },
                {
                    time = 12.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 13.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 72.0,
                },
                {
                    time = 13.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 13.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 69.0,
                },
                {
                    time = 13.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 14.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 60.0,
                },
                {
                    time = 14.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 14.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 69.0,
                },
                {
                    time = 14.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 15.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 72.0,
                },
                {
                    time = 15.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 71.0,
                },
                {
                    time = 15.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 69.0,
                },
                {
                    time = 15.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 64.0,
                },
                {
                    time = 15.761111111111,
                    note = 71.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.766666666667,
                    note = 69.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.766666666667,
                    note = 72.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.769444444444,
                    note = 60.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.772222222222,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
            },
        },
        {
            loop_length = 16,
            events = {
                {
                    time = 0.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 0.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 0.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 0.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 1.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 1.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 1.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 1.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 2.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 2.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 2.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 2.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 3.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 3.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 3.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 3.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 4.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 4.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 4.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 54.0,
                },
                {
                    time = 4.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 5.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 5.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 54.0,
                },
                {
                    time = 5.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 5.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 6.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 54.0,
                },
                {
                    time = 6.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 6.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 6.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 54.0,
                },
                {
                    time = 7.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 7.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 7.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 54.0,
                },
                {
                    time = 7.7166666666667,
                    note = 54.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 8.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 55.0,
                },
                {
                    time = 8.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 8.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 8.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 55.0,
                },
                {
                    time = 9.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 9.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 9.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 55.0,
                },
                {
                    time = 9.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 10.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 10.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 55.0,
                },
                {
                    time = 10.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 10.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 11.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 55.0,
                },
                {
                    time = 11.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 11.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 11.744444444444,
                    note = 55.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 11.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 12.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 12.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 12.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 57.0,
                },
                {
                    time = 12.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 13.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 13.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 57.0,
                },
                {
                    time = 13.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 13.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 14.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 57.0,
                },
                {
                    time = 14.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 14.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 14.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 57.0,
                },
                {
                    time = 15.0,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 15.25,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 47.0,
                },
                {
                    time = 15.5,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 57.0,
                },
                {
                    time = 15.75,
                    velocity = 100,
                    type = "note",
                    duration = 0.2,
                    note = 59.0,
                },
                {
                    time = 15.863888888889,
                    note = 47.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.866666666667,
                    note = 59.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.880555555556,
                    note = 57.0,
                    velocity = 0.0,
                    type = "note",
                },
            },
        },
        {
            loop_length = 16,
            events = {
                {
                    time = 0.0027777777777778,
                    note = 79.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 0.21111111111111,
                    note = 79.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 0.21111111111111,
                    note = 79.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 0.35,
                    note = 76.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 0.51666666666667,
                    note = 76.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 0.51666666666667,
                    note = 76.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 0.76666666666667,
                    note = 83.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 1.0444444444444,
                    note = 83.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 1.0444444444444,
                    note = 83.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.0,
                    note = 71.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 2.15,
                    note = 71.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.15,
                    note = 71.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.2472222222222,
                    note = 69.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 2.325,
                    note = 69.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.325,
                    note = 69.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.5083333333333,
                    note = 67.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 2.5833333333333,
                    note = 67.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.5833333333333,
                    note = 67.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.7277777777778,
                    note = 66.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 2.8305555555556,
                    note = 66.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.8305555555556,
                    note = 66.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.9972222222222,
                    note = 64.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 3.2472222222222,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 3.2472222222222,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.5,
                    note = 78.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 7.6722222222222,
                    note = 78.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.6722222222222,
                    note = 78.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 8.0027777777778,
                    note = 79.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 8.1944444444444,
                    note = 79.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 8.1944444444444,
                    note = 79.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 8.3611111111111,
                    note = 76.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 8.5444444444444,
                    note = 76.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 8.5444444444444,
                    note = 76.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 8.7444444444444,
                    note = 83.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 9.05,
                    note = 83.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 9.05,
                    note = 83.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.0,
                    note = 71.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 10.122222222222,
                    note = 71.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.122222222222,
                    note = 71.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.247222222222,
                    note = 69.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 10.308333333333,
                    note = 69.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.308333333333,
                    note = 69.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.516666666667,
                    note = 67.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 10.569444444444,
                    note = 67.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.569444444444,
                    note = 67.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.733333333333,
                    note = 66.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 10.819444444444,
                    note = 66.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.819444444444,
                    note = 66.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.980555555556,
                    note = 64.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 11.238888888889,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 11.238888888889,
                    note = 64.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.502777777778,
                    note = 78.0,
                    velocity = 100.0,
                    type = "note",
                },
                {
                    time = 15.727777777778,
                    note = 78.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.727777777778,
                    note = 78.0,
                    velocity = 0.0,
                    type = "note",
                },
            },
        },
        {
            loop_length = 16,
            events = {
                {
                    time = 0.0,
                    velocity = 100,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 0.25,
                    velocity = 100,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 0.5,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 0.75,
                    velocity = 100,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 0.87222222222222,
                    note = 52.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 1.0,
                    velocity = 60,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 1.25,
                    velocity = 60,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 1.25,
                    velocity = 60,
                    note = 55,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 1.2944444444444,
                    note = 54.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 1.5,
                    velocity = 100,
                    note = 55,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 1.6638888888889,
                    note = 55.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 2.0,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 2.25,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 2.5,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 2.75,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 2.8583333333333,
                    note = 52.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 3.0,
                    velocity = 100,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 3.2416666666667,
                    note = 54.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 3.25,
                    velocity = 100,
                    note = 55,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 3.5,
                    velocity = 60,
                    note = 55,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 3.5833333333333,
                    note = 55.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 4.0,
                    velocity = 60,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 4.25,
                    velocity = 100,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 4.5,
                    velocity = 60,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 4.75,
                    velocity = 60,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 4.7861111111111,
                    note = 50.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 5.0,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 5.2472222222222,
                    note = 52.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 5.25,
                    velocity = 100,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 5.5,
                    velocity = 60,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 5.75,
                    velocity = 60,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 5.9166666666667,
                    note = 54.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 6.0,
                    velocity = 100,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 6.25,
                    velocity = 100,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 6.5,
                    velocity = 60,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 6.7111111111111,
                    note = 50.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.0,
                    velocity = 100,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 7.25,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 7.25,
                    velocity = 100,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 7.2611111111111,
                    note = 52.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 7.5,
                    velocity = 60,
                    note = 54,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 7.625,
                    note = 54.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 8.0,
                    velocity = 100,
                    note = 48,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 8.25,
                    velocity = 60,
                    note = 48,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 8.5,
                    velocity = 100,
                    note = 48,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 8.75,
                    velocity = 100,
                    note = 48,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 8.9555555555556,
                    note = 48.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 9.0,
                    velocity = 100,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 9.25,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 9.25,
                    velocity = 100,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 9.2527777777778,
                    note = 50.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 9.5,
                    velocity = 100,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 9.75,
                    velocity = 100,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 9.8138888888889,
                    note = 52.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 10.25,
                    velocity = 60,
                    note = 48,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 10.5,
                    velocity = 60,
                    note = 48,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 10.75,
                    velocity = 100,
                    note = 48,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 10.941666666667,
                    note = 48.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 11.0,
                    velocity = 100,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 11.25,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 11.25,
                    velocity = 60,
                    note = 50,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 11.269444444444,
                    note = 50.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 11.5,
                    velocity = 60,
                    note = 52,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 11.669444444444,
                    note = 52.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 12.0,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 12.25,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 12.5,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 12.75,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 13.0,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 13.25,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 13.5,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 13.75,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 14.0,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 14.25,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 14.5,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 14.5,
                    velocity = 100,
                    note = 51,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 14.75,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 14.75,
                    velocity = 100,
                    note = 51,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.0,
                    velocity = 100,
                    note = 51,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.0,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.25,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.25,
                    velocity = 100,
                    note = 51,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.5,
                    velocity = 60,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.5,
                    velocity = 100,
                    note = 51,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.75,
                    velocity = 100,
                    note = 51,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.75,
                    velocity = 100,
                    note = 47,
                    duration = 0.2,
                    type = "note",
                },
                {
                    time = 15.958333333333,
                    note = 47.0,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    time = 15.966666666667,
                    note = 51.0,
                    velocity = 0.0,
                    type = "note",
                },
            },
        },
    },
    bpm = 75.0,
    knob2 = 0.97849464416504,
    transpose = -24,
    track_levels = {
        0.90224826335907,
        0.90127074718475,
        0.95405668020248,
        1.0,
    },
    knob3 = 0.19354838132858,
    master_loop_length = 16,
    pattern = 2,
    velocity_mode = 5,
    metro_mode = 1,
    knob1 = 1.0,
    selected_track = 4,
}
