return {
    knob1 = 0.69012707471848,
    metro_mode = 1,
    knob2 = 0.52492666244507,
    velocity_mode = 3,
    track_levels = {
        1.0,
        1.0,
        1.0,
        1,
    },
    knob3 = 0.3998045027256,
    sequences = {
        {
            events = {
                {
                    note = 66.0,
                    duration = 0.2,
                    time = 0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 0.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 0.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 0.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 66.0,
                    duration = 0.2,
                    time = 1.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 1.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 1.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 1.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 66.0,
                    duration = 0.2,
                    time = 2.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 2.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 2.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 2.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 66.0,
                    duration = 0.2,
                    time = 3.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 3.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 3.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 3.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 66,
                    time = 3.9277777777778,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 74,
                    time = 3.9277777777778,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 69,
                    time = 3.9277777777778,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 65.0,
                    duration = 0.2,
                    time = 4.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 4.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 4.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 4.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 65.0,
                    duration = 0.2,
                    time = 5.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 5.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 5.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 5.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 65.0,
                    duration = 0.2,
                    time = 6.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 6.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 6.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 6.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 65.0,
                    duration = 0.2,
                    time = 7.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 7.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 7.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 7.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69,
                    time = 7.9777777777778,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 65,
                    time = 7.9777777777778,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 74,
                    time = 7.9777777777778,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 8.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 8.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 8.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 8.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 9.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 9.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 9.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 9.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 10.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 10.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 10.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 10.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 11.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 11.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 11.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 11.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69,
                    time = 11.908333333333,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 64,
                    time = 11.908333333333,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 74,
                    time = 11.908333333333,
                    velocity = 0,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 12.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 12.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 73.0,
                    duration = 0.2,
                    time = 12.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 12.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 13.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 13.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 73.0,
                    duration = 0.2,
                    time = 13.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 13.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 14.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 14.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 73.0,
                    duration = 0.2,
                    time = 14.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 14.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 64.0,
                    duration = 0.2,
                    time = 15.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 15.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 73.0,
                    duration = 0.2,
                    time = 15.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 69.0,
                    duration = 0.2,
                    time = 15.75,
                    velocity = 100,
                    type = "note",
                },
            },
            loop_length = 16,
        },
        {
            events = {
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 0.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 0.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 1.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 1.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 1.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 1.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 2.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 2.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 2.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 2.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 3.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 3.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 3.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 3.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    time = 3.875,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 80.0,
                    duration = 0.2,
                    time = 4.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 80.0,
                    duration = 0.2,
                    time = 4.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 80.0,
                    duration = 0.2,
                    time = 4.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 80.0,
                    duration = 0.2,
                    time = 4.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 80.0,
                    duration = 0.2,
                    time = 5.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 80.0,
                    duration = 0.2,
                    time = 5.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 80.0,
                    time = 5.4944444444444,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 5.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 5.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 6.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 6.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 6.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 6.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 7.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    duration = 0.2,
                    time = 7.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 81.0,
                    time = 7.4083333333333,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 8.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 8.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 9.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 9.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 9.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 9.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 10.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 10.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 10.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 10.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 11.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 11.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    duration = 0.2,
                    time = 11.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 76.0,
                    time = 11.580555555556,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 12.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 12.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 12.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 12.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 13.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 13.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 13.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 13.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 14.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 14.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 14.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 14.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 15.0,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 15.25,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 74.0,
                    duration = 0.2,
                    time = 15.5,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    duration = 0.2,
                    time = 15.75,
                    velocity = 100,
                    type = "note",
                },
                {
                    note = 78.0,
                    time = 15.783333333333,
                    velocity = 0.0,
                    type = "note",
                },
                {
                    note = 74.0,
                    time = 15.825,
                    velocity = 0.0,
                    type = "note",
                },
            },
            loop_length = 16,
        },
    },
    selected_track = 2,
    knob4 = 0.811339199543,
    transpose = 0,
    master_loop_length = 16,
    pattern = 1,
}
