return {
    pattern = 1,
    transpose = 0,
    selected_track = 2,
    knob4 = 0.811339199543,
    knob1 = 0.76441836357117,
    knob2 = 0.52492666244507,
    bpm = 100.0,
    velocity_mode = 5,
    master_loop_length = 32,
    track_levels = {
        0.64613878726959,
        1.0,
        0.88269793987274,
        1.0,
    },
    metro_mode = 1,
    knob3 = 0.3998045027256,
    sequences = {
        {
            events = {
                {
                    time = 0,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 0.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 0.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 0.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 1.0,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 1.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 1.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 1.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 2.0,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 2.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 2.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 2.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 3.0,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 3.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 3.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 3.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    velocity = 0,
                    time = 3.9277777777778,
                    note = 74,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 3.9277777777778,
                    note = 69,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 3.9277777777778,
                    note = 66,
                    type = "note",
                },
                {
                    time = 4.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 4.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 4.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 4.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 5.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 5.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 5.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 5.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 6.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 6.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 6.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 6.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 7.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 7.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 7.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 7.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    velocity = 0,
                    time = 7.9777777777778,
                    note = 74,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 7.9777777777778,
                    note = 65,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 7.9777777777778,
                    note = 69,
                    type = "note",
                },
                {
                    time = 8.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 8.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 8.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 8.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 9.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 9.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 9.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 9.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 10.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 10.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 10.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 10.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 11.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 11.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 11.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 11.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    velocity = 0,
                    time = 11.908333333333,
                    note = 74,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 11.908333333333,
                    note = 64,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 11.908333333333,
                    note = 69,
                    type = "note",
                },
                {
                    time = 12.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 12.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 12.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 12.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 13.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 13.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 13.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 13.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 14.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 14.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 14.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 14.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 15.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 15.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 15.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 15.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 16,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 16.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 16.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 16.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 17.0,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 17.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 17.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 17.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 18.0,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 18.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 18.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 18.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 19.0,
                    duration = 0.2,
                    type = "note",
                    note = 66.0,
                    velocity = 100,
                },
                {
                    time = 19.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 19.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 19.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    velocity = 0,
                    time = 19.927777777778,
                    note = 69,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 19.927777777778,
                    note = 74,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 19.927777777778,
                    note = 66,
                    type = "note",
                },
                {
                    time = 20.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 20.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 20.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 20.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 21.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 21.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 21.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 21.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 22.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 22.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 22.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 22.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 23.0,
                    duration = 0.2,
                    type = "note",
                    note = 65.0,
                    velocity = 100,
                },
                {
                    time = 23.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 23.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 23.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    velocity = 0,
                    time = 23.977777777778,
                    note = 74,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 23.977777777778,
                    note = 65,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 23.977777777778,
                    note = 69,
                    type = "note",
                },
                {
                    time = 24.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 24.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 24.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 24.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 25.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 25.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 25.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 25.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 26.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 26.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 26.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 26.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 27.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 27.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 27.5,
                    duration = 0.2,
                    type = "note",
                    note = 74.0,
                    velocity = 100,
                },
                {
                    time = 27.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    velocity = 0,
                    time = 27.908333333333,
                    note = 74,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 27.908333333333,
                    note = 64,
                    type = "note",
                },
                {
                    velocity = 0,
                    time = 27.908333333333,
                    note = 69,
                    type = "note",
                },
                {
                    time = 28.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 28.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 28.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 28.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 29.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 29.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 29.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 29.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 30.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 30.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 30.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 30.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 31.0,
                    duration = 0.2,
                    type = "note",
                    note = 64.0,
                    velocity = 100,
                },
                {
                    time = 31.25,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
                {
                    time = 31.5,
                    duration = 0.2,
                    type = "note",
                    note = 73.0,
                    velocity = 100,
                },
                {
                    time = 31.75,
                    duration = 0.2,
                    type = "note",
                    note = 69.0,
                    velocity = 100,
                },
            },
            loop_length = 32,
        },
        {
            events = {
                {
                    velocity = 100.0,
                    time = 0.98888888888889,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 2.975,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 2.975,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 2.9916666666667,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 3.5527777777778,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 3.5861111111111,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 3.5861111111111,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 5.7083333333333,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 5.7083333333333,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 5.7166666666667,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 5.7305555555556,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 5.7305555555556,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 5.9666666666667,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 9.9138888888889,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 9.9138888888889,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 11.961111111111,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 12.991666666667,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 13.05,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 13.05,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 13.811111111111,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 13.811111111111,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 13.916666666667,
                    note = 68.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 14.405555555556,
                    note = 68.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 14.405555555556,
                    note = 68.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 14.730555555556,
                    note = 69.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 15.108333333333,
                    note = 69.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 15.108333333333,
                    note = 69.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 15.480555555556,
                    note = 66.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 15.997222222222,
                    note = 66.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 15.997222222222,
                    note = 66.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 17.019444444444,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 18.997222222222,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 19.047222222222,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 19.047222222222,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 19.522222222222,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 19.547222222222,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 19.547222222222,
                    note = 71.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 21.444444444444,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 21.444444444444,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 21.508333333333,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 23.441666666667,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 23.441666666667,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 28.469444444444,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 28.966666666667,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 29.425,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 29.425,
                    note = 73.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 29.447222222222,
                    note = 76.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 29.680555555556,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 29.680555555556,
                    note = 74.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 29.727777777778,
                    note = 78.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 30.122222222222,
                    note = 76.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 30.122222222222,
                    note = 76.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 30.455555555556,
                    note = 80.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 30.472222222222,
                    note = 78.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 30.472222222222,
                    note = 78.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 30.680555555556,
                    note = 80.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 30.680555555556,
                    note = 80.0,
                    type = "note",
                },
                {
                    velocity = 100.0,
                    time = 31.491666666667,
                    note = 81.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 31.797222222222,
                    note = 81.0,
                    type = "note",
                },
                {
                    velocity = 0.0,
                    time = 31.797222222222,
                    note = 81.0,
                    type = "note",
                },
            },
            loop_length = 32,
        },
    },
}
